services:
  - type: web
    name: yunuki-backend
    env: node
    region: frankfurt
    plan: free
    rootDir: .
    buildCommand: npm install && npx nest build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 10000
      - key: DB_TYPE
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: yunuki-db
          property: HOST
      - key: DB_PORT
        fromDatabase:
          name: yunuki-db
          property: PORT
      - key: DB_USERNAME
        fromDatabase:
          name: yunuki-db
          property: USER
      - key: DB_PASSWORD
        fromDatabase:
          name: yunuki-db
          property: PASSWORD
      - key: DB_DATABASE
        fromDatabase:
          name: yunuki-db
          property: DATABASE
    databases:
      - name: yunuki-db
        plan: free
